# Canonical license fingerprint metadata for MANIFEST/license-spdx-match.
#
# SPDX: LicenseRef-PolyForm-Noncommercial-1.0.0
# Fleet-shared: kanon, logismos, and private downstream consumers.

[sha256]
LICENSE = "60cd10e4f7e2e2f98514f157b34e0ebf62d4a7828324b255656e1fb093dcdb0a"
