//! # hipcore
//!
//! HIP FFI + device / stream / event / memory primitives.
//!
//! ## API
//!
//! - Direct FFI bindings generated by `bindgen` against the installed HIP
//!   headers (`build.rs`).
//! - [`Device`] — ordinal, capability detection, memory budget.
//! - [`DeviceBuffer<T>`] — owned device allocation with safe `Drop`.
//! - [`Stream`] and [`Event`] — async dispatch primitives.
//! - Typed [`Error`] enum; no `panic` / `unwrap` / `expect` outside
//!   `#[cfg(test)]`.
//!
//! `taxis` and the GPU-enabled `kernels`/`praxis` graph consume this
//! boundary; pure CPU consumers do not require it. Nothing else in
//! logismos binds HIP.

#![deny(missing_docs)]
#![deny(unsafe_op_in_unsafe_fn)]
#![allow(
    clippy::module_name_repetitions,
    clippy::map_unwrap_or,
    clippy::must_use_candidate,
    clippy::default_trait_access,
    clippy::cast_sign_loss,
    clippy::cast_possible_wrap,
    clippy::cast_possible_truncation,
    clippy::cast_lossless,
    clippy::cast_precision_loss,
    clippy::borrow_as_ptr,
    clippy::doc_markdown,
    clippy::needless_pass_by_value,
    clippy::ptr_as_ptr,
    clippy::ref_as_ptr,
    clippy::items_after_statements,
    clippy::too_many_lines
)]

pub mod device;
pub mod error;
pub mod ffi;
pub mod memory;
pub mod pod;
pub mod stream;
pub mod teardown;

pub use crate::device::{
    Device, DeviceIdentity, DeviceInfo, DeviceProps, DeviceSelector, DeviceUuid, MemoryBudget,
    PciBusId, enumerate_devices,
};
pub use crate::error::{Error, ErrorKind, Result, check};
pub use crate::memory::{
    BufferRelease, BufferTeardownQuarantine, DeviceBuffer, PendingBufferTeardown, PendingCopy,
    TeardownBuffer,
};
pub use crate::pod::BytePod;
pub use crate::stream::{
    Event, NonOwnedStream, PendingStreamDestroy, PendingStreamQuiesce, QuiescentStream, Stream,
    StreamQuiesce, StreamRelease, StreamSynchronizationUnconfirmed, StreamTeardownQuarantine,
};
pub use crate::teardown::{
    InventoryAccountingError, InventoryEvidence, InventoryPushError, InventoryQuarantine,
    InventoryReceipt, InventoryRelease, InventorySynchronizationUnconfirmed, PendingInventory,
    ReleaseReceipt, ResourceKind, ResourceMetadata, TeardownEntryId, TeardownError,
    TeardownInventory, TeardownPhase, TeardownTombstone,
};
