//! # hipcore
//!
//! HIP FFI + device / stream / event / memory primitives. Tier-1
//! foundation of the logismos platform — the lowest layer we own.
//!
//! ## Phase 1 scope
//!
//! - Direct FFI bindings generated by `bindgen` against ROCm 6.4
//!   headers (`build.rs`).
//! - [`Device`] — ordinal, capability detection, memory budget.
//! - [`DeviceBuffer<T>`] — owned device allocation with safe `Drop`.
//! - [`Stream`] and [`Event`] — async dispatch primitives.
//! - Typed [`Error`] enum; no `panic` / `unwrap` / `expect` outside
//!   `#[cfg(test)]`.
//!
//! Every other tier-1 crate (`taxis`, `kernels`, `praxis`) depends on
//! this crate; nothing else in logismos binds HIP.
//!
//! Dossier `~/dev/kanon/projects/logismos/research/01-rocm-hip-rdna3.md`
//! locks the design decisions; see
//! `~/dev/kanon/projects/logismos/phases/01-foundation/PLAN.md` for
//! per-item acceptance criteria.

#![deny(missing_docs)]
#![deny(unsafe_op_in_unsafe_fn)]
#![allow(
    clippy::module_name_repetitions,
    clippy::map_unwrap_or,
    clippy::must_use_candidate,
    clippy::default_trait_access,
    clippy::cast_sign_loss,
    clippy::cast_possible_wrap,
    clippy::cast_possible_truncation,
    clippy::cast_lossless,
    clippy::cast_precision_loss,
    clippy::borrow_as_ptr,
    clippy::doc_markdown,
    clippy::needless_pass_by_value,
    clippy::ptr_as_ptr,
    clippy::ref_as_ptr,
    clippy::items_after_statements,
    clippy::too_many_lines
)]

pub mod device;
pub mod error;
pub mod ffi;
pub mod memory;
pub mod pod;
pub mod stream;

pub use crate::device::{Device, DeviceProps, MemoryBudget, PciBusId};
pub use crate::error::{Error, ErrorKind, Result, check};
pub use crate::memory::DeviceBuffer;
pub use crate::pod::BytePod;
pub use crate::stream::{Event, Stream};
